#!/bin/bash

helptxt="Употреба: fakeprogress [ЦЕЛЕВО ЧИСЛО] [ИНТЕРВАЛ НА БРОЕНЕ] [ТЕКСТ МЕЖДУ] [ТЕКСТ НАКРАЯ]"
inbtw="от общо"
endtxt="Готово!"

if [ "$#" -lt 2 ] || [ "$#" -gt 4 ]; then
    echo "$helptxt"
    exit
else
    if [[ ! $1 =~ ^[0-9]+$ ]]; then
        echo "$helptxt"
        exit
    fi
    if [[ ! "$2" =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
        echo "$helptxt"
        exit
    fi
    if [[ -n "$3" ]]; then
        inbtw="$3"
    fi
    if [[ -n "$4" ]]; then
        endtxt="$4"
    fi
fi

for ((x=1; x<=$1; x++)); do printf "\r$x $inbtw $1"; sleep $2; done; echo -e "\n$endtxt"
